"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { Card, ComboKind, PublicGameState, Suit } from "../lib/game";
import "./game.css";

type Session = { code: string; playerId: string; token: string; name: string; seat: number };
type Snapshot = { room: { code: string; status: string; version: number }; player: { id: string; name: string; seat: number }; token?: string; game: PublicGameState };
type LobbyMessage = { id: number; name: string; text: string; roomCode?: string | null; createdAt: string };
const STORE = "murlan-session-v1";
const suitName: Record<Suit, string> = { H: "Cuori", D: "Quadri", C: "Fiori", S: "Picche", X: "Jolly" };
const kindName: Record<ComboKind, string> = { single: "Singola", pair: "Coppia", triple: "Tris", straight: "Scala", "triple-run": "Scala con tris", "five-pairs": "Scala di 5 coppie", bomb: "Bomba", "straight-flush": "Scala reale" };
const rankFile: Record<string, string> = { "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10", J: "jack", Q: "queen", K: "king", A: "ace", "2": "2" };
const suitFile: Record<string, string> = { H: "hearts", D: "diamonds", C: "clubs", S: "spades" };
const order = ["3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A", "2", "BJ", "RJ"];
function cardImage(card: Card) { if (card.rank === "BJ") return "/cards/joker_black_v4.webp"; if (card.rank === "RJ") return "/cards/joker_red_v4.webp"; return `/cards/${rankFile[card.rank]}_of_${suitFile[card.suit]}.svg`; }
function CardView({ card, selected, small, onClick }: { card: Card; selected?: boolean; small?: boolean; onClick?: () => void }) {
  const label = card.suit === "X" ? suitName.X : `${card.rank} di ${suitName[card.suit]}`;
  return <button type="button" className={`playing-card ${selected ? "selected" : ""} ${small ? "small" : ""}`} onClick={onClick} disabled={!onClick} aria-label={label}><img src={cardImage(card)} alt="" /></button>;
}

export default function Home() {
  const [session, setSession] = useState<Session | null>(null); const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [name, setName] = useState(""); const [code, setCode] = useState(""); const [humans, setHumans] = useState(1); const [selected, setSelected] = useState<string[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [showRules, setShowRules] = useState(false); const [copied, setCopied] = useState(false);
  const game = snapshot?.game; const myTurn = !!game && game.phase === "playing" && game.turn === session?.seat;
  const sortedHand = useMemo(() => [...(game?.hand ?? [])].sort((a, b) => order.indexOf(a.rank) - order.indexOf(b.rank) || "HDCSX".indexOf(a.suit) - "HDCSX".indexOf(b.suit)), [game?.hand]);
  const saveSession = (next: Session) => { setSession(next); localStorage.setItem(STORE, JSON.stringify(next)); };
  const request = useCallback(async (url: string, init?: RequestInit) => { const res = await fetch(url, init); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? "Qualcosa è andato storto."); return data as Snapshot; }, []);
  const refresh = useCallback(async (active: Session) => { try { const data = await request(`/api/rooms?code=${active.code}&playerId=${active.playerId}&token=${active.token}`); setSnapshot(data); } catch { /* session may have expired */ } }, [request]);
  useEffect(() => { const raw = localStorage.getItem(STORE); const query = new URLSearchParams(location.search).get("room"); if (query) setCode(query.toUpperCase()); if (raw) { try { const active = JSON.parse(raw) as Session; saveSession(active); refresh(active); } catch { localStorage.removeItem(STORE); } } }, [refresh]);
  useEffect(() => { if (!session) return; const timer = setInterval(() => refresh(session), 1800); return () => clearInterval(timer); }, [session, refresh]);

  async function enter(operation: "create" | "join") {
    setBusy(true); setError("");
    try { const data = await request("/api/rooms", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation, name, code, humanCount: humans }) }); const active = { code: data.room.code, playerId: data.player.id, token: data.token!, name: data.player.name, seat: data.player.seat }; saveSession(active); setSnapshot(data); history.replaceState({}, "", `?room=${data.room.code}`); }
    catch (e) { setError(e instanceof Error ? e.message : "Errore inatteso."); } finally { setBusy(false); }
  }
  async function action(type: "play" | "pass" | "new-hand") {
    if (!session || !snapshot) return; setBusy(true); setError("");
    try { const data = await request("/api/rooms", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: session.code, playerId: session.playerId, token: session.token, version: snapshot.room.version, action: { type, cardIds: type === "play" ? selected : undefined } }) }); setSnapshot(data); setSelected([]); }
    catch (e) { setError(e instanceof Error ? e.message : "Errore inatteso."); await refresh(session); } finally { setBusy(false); }
  }
  async function share() { const url = `${location.origin}${location.pathname}?room=${session?.code}`; await navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 1800); }
  function leave() { localStorage.removeItem(STORE); setSession(null); setSnapshot(null); setSelected([]); history.replaceState({}, "", location.pathname); }

  if (!session || !snapshot) return <><main className="landing">
    <nav><span className="wordmark">murlan-game.dev</span><button className="text-button" onClick={() => setShowRules(true)}>Come si gioca</button></nav>
    <section className="hero">
      <div className="hero-copy"><p className="eyebrow">Il classico dalmata · online</p><h1>MURLAN</h1><p className="tagline">Quattro giocatori. Due squadre.<br />Una sola carta può cambiare il tavolo.</p><div className="suits" aria-hidden="true"><span>♥</span><span>♦</span><span>♣</span><span>♠</span></div></div>
      <div className="entry-card"><div className="entry-tabs"><span>NUOVA PARTITA</span><span>ENTRA</span></div><label>Il tuo nome<input value={name} onChange={(e) => setName(e.target.value)} maxLength={24} placeholder="Come ti chiami?" /></label><label>Quante persone giocano?<div className="people-picker">{[1,2,3,4].map((n) => <button key={n} type="button" onClick={() => setHumans(n)} className={humans === n ? "active" : ""}><b>{n}</b><small>{n === 1 ? "tu + 3 bot" : n === 4 ? "tutti umani" : `${n} umani`}</small></button>)}</div></label><button className="primary" disabled={busy || !name.trim()} onClick={() => enter("create")}>Crea la stanza</button><div className="or"><span>oppure entra con un codice</span></div><div className="join-row"><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} maxLength={6} placeholder="CODICE" /><button disabled={busy || !name.trim() || code.length < 4} onClick={() => enter("join")}>Entra</button></div>{error && <p className="error">{error}</p>}<p className="microcopy">Nessun download. Funziona su iPhone, Android e desktop.</p></div>
    </section><footer><span>Edizione 2026</span><span>Gioca responsabilmente, passa strategicamente.</span></footer>{showRules && <Rules onClose={() => setShowRules(false)} />}
  </main><Lobby name={name} onJoin={(room) => setCode(room)} /></>;

  if (game?.phase === "waiting") return <><main className="room-wait"><nav><span className="wordmark">murlan-game.dev</span><button className="text-button" onClick={leave}>Esci</button></nav><section className="waiting-panel"><p className="eyebrow">Sala d’attesa</p><h1>Raduna il tavolo</h1><p>Servono ancora {game.humanCount - game.players.length} {game.humanCount - game.players.length === 1 ? "giocatore" : "giocatori"}. Gli altri posti saranno affidati ai bot.</p><div className="room-code"><small>Codice stanza</small><strong>{session.code}</strong></div><button className="primary" onClick={share}>{copied ? "Link copiato!" : "Copia link d’invito"}</button><div className="seat-preview">{Array.from({ length: 4 }, (_, seat) => <div key={seat} className={`seat team-${seat % 2}`}><span>{game.players[seat]?.name ?? (seat < game.humanCount ? "In attesa…" : `Bot ${seat + 1}`)}</span><small>Squadra {seat % 2 ? "Giada" : "Ambra"}</small></div>)}</div></section></main><Lobby name={session.name} roomCode={session.code} onJoin={() => {}} /></>;

  return <><main className="game-shell">
    <header className="game-header"><button className="brand-button" onClick={leave}>M</button><div className="score amber"><small>Squadra Ambra</small><b>{game?.scores[0]}</b></div><div className="target"><small>Traguardo</small><b>{game?.target}</b></div><div className="score jade"><b>{game?.scores[1]}</b><small>Squadra Giada</small></div><button className="icon-button" onClick={() => setShowRules(true)}>?</button></header>
    <section className="table">
      <div className="players-ring">{game?.players.map((player, seat) => <div key={seat} className={`player-pill p${seat} team-${player.team} ${game.turn === seat ? "turn" : ""} ${game.finishOrder.includes(seat) ? "finished" : ""}`}><span className="avatar">{player.bot ? "◆" : player.name.slice(0,1).toUpperCase()}</span><div><b>{player.name}{seat === session.seat ? " · Tu" : ""}</b><small>{game.finishOrder.includes(seat) ? `${game.finishOrder.indexOf(seat)+1}° posto` : player.cards === 1 ? "ULTIMA MANO!" : `${player.cards} carte`}</small></div></div>)}</div>
      <div className="table-center"><p className="turn-label">{game?.phase === "playing" ? myTurn ? "Tocca a te" : `Turno di ${game?.players[game.turn]?.name}` : game?.phase === "match-over" ? "Partita conclusa" : "Mano conclusa"}</p><div className="last-play">{game?.currentPlay ? <><small>{kindName[game.currentPlay.kind]} · {game.players[game.currentPlay.seat].name}</small><div>{game.currentPlay.cards.map((card) => <CardView card={card} small key={card.id} />)}</div></> : <div className="empty-play"><span>♠</span><p>Nuovo giro<br /><small>gioca una combinazione libera</small></p></div>}</div>{game?.passes.length ? <p className="pass-line">Hanno passato: {game.passes.map((s) => game.players[s].name).join(", ")}</p> : null}</div>
    </section>
    <section className="hand-area"><div className="hand-meta"><span>La tua mano · {sortedHand.length} carte</span><span>{selected.length ? `${selected.length} selezionate` : "Seleziona le carte da giocare"}</span></div><div className="hand-scroll">{sortedHand.map((card) => <CardView key={card.id} card={card} selected={selected.includes(card.id)} onClick={myTurn ? () => setSelected((old) => old.includes(card.id) ? old.filter((id) => id !== card.id) : [...old, card.id]) : undefined} />)}</div><div className="actions">{game?.phase === "playing" ? <><button className="pass" disabled={!myTurn || !game.currentPlay || busy} onClick={() => action("pass")}>Passo</button><button className="primary play" disabled={!myTurn || !selected.length || busy} onClick={() => action("play")}>Gioca {selected.length || ""}</button></> : game?.phase === "hand-over" ? <button className="primary play" disabled={busy} onClick={() => action("new-hand")}>Nuova mano</button> : <button className="primary play" onClick={leave}>Torna all’inizio</button>}</div>{error && <p className="error action-error">{error}</p>}</section>
    <aside className="activity"><b>Diario del tavolo</b>{game?.log.slice(0,5).map((line, i) => <p key={i}>{line}</p>)}</aside>{showRules && <Rules onClose={() => setShowRules(false)} />}
  </main><Lobby name={session.name} roomCode={session.code} onJoin={() => {}} /></>;
}

function Rules({ onClose }: { onClose: () => void }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="rules"><header><div><p className="eyebrow">Regolamento 2026</p><h2>Come si gioca a Murlan</h2></div><button onClick={onClose}>×</button></header><div className="rules-body"><p>Libera la mano prima degli avversari. In questa versione i posti opposti formano una squadra: Ambra (1 e 3) contro Giada (2 e 4).</p><details open><summary>Ordine e apertura</summary><p>3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A, 2, Jolly Nero, Jolly Rosso. I semi valgono ♠ Picche &gt; ♣ Fiori &gt; ♦ Quadri &gt; ♥ Cuori. La prima giocata deve contenere il 3♠.</p></details><details><summary>Combinazioni</summary><p>Singola, coppia, tris, scala di almeno 5 carte, scala con tris centrale e singole agli estremi, oppure cinque coppie consecutive. Devi rispondere con lo stesso tipo e numero di carte, ma più alto.</p></details><details><summary>Bomba e Scala Reale</summary><p>Quattro carte dello stesso valore formano una Bomba. Cinque carte consecutive dello stesso seme formano una Scala Reale. Entrambe interrompono una combinazione ordinaria.</p></details><details><summary>Passo e chiusura</summary><p>Puoi passare anche per strategia. Dopo che tutti gli altri passano, l’ultima persona ad aver giocato apre un nuovo giro. Con una sola carta il tavolo mostra automaticamente “Ultima mano”.</p></details><details><summary>Punteggio a squadre</summary><p>Le posizioni valgono 3, 2, 1 e 0 punti. I punti dei compagni si sommano. Il primo traguardo è 21; se entrambe le squadre lo raggiungono nella stessa mano, sale a 31, poi 41 e 51.</p></details><details><summary>Scambio dalla seconda mano</summary><p>L’ultimo classificato cede la carta più alta al primo, che restituisce una carta tra 3 e 10. Se l’ultimo possiede entrambi i Jolly, lo scambio non avviene.</p></details></div></section></div>; }

function Lobby({ name, roomCode, onJoin }: { name: string; roomCode?: string; onJoin: (code: string) => void }) {
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState<LobbyMessage[]>([]); const [text, setText] = useState(""); const [unread, setUnread] = useState(0); const [ready, setReady] = useState(false);
  const latest = messages.at(-1)?.id ?? 0;
  const load = useCallback(async () => { try { const res = await fetch(`/api/lobby${latest ? `?since=${latest}` : ""}`); if (!res.ok) return; const data = await res.json() as { messages: LobbyMessage[] }; if (!data.messages.length) { setReady(true); return; } setMessages((old) => latest ? [...old, ...data.messages].slice(-60) : data.messages); if (ready && !open) { setUnread((n) => n + data.messages.length); const last = data.messages.at(-1)!; if (document.hidden && "Notification" in window && Notification.permission === "granted") new Notification(`${last.name} nella lobby Murlan`, { body: last.text, icon: "/icon-192.png" }); } setReady(true); } catch { /* lobby is optional */ } }, [latest, open, ready]);
  useEffect(() => { load(); const timer = setInterval(load, 4500); return () => clearInterval(timer); }, [load]);
  useEffect(() => { if (open) setUnread(0); }, [open]);
  async function enableNotifications() { if ("Notification" in window) await Notification.requestPermission(); }
  async function send(invite = false) { if (!name.trim() || (!text.trim() && !invite)) return; const message = invite ? "Vuoi giocare? Entra nella mia stanza." : text; const res = await fetch("/api/lobby", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, text: message, roomCode: invite ? roomCode : undefined }) }); if (res.ok) { setText(""); await load(); } }
  return <><button className="lobby-bell" onClick={() => setOpen((v) => !v)} aria-label="Apri la lobby"><span>♟</span> Lobby chat {unread > 0 && <b>{unread}</b>}</button>{open && <aside className="lobby-panel"><header><div><strong>Lobby Murlan</strong><small>Organizza una partita</small></div><button onClick={() => setOpen(false)}>×</button></header><div className="lobby-feed">{messages.length ? messages.map((m) => <article key={m.id}><div><b>{m.name}</b><time>{new Date(m.createdAt).toLocaleTimeString("it-IT", { hour: "2-digit", minute: "2-digit" })}</time></div><p>{m.text}</p>{m.roomCode && <button onClick={() => { onJoin(m.roomCode!); setOpen(false); }}>Entra · {m.roomCode}</button>}</article>) : <p className="lobby-empty">La lobby è silenziosa. Rompi il ghiaccio.</p>}</div><div className="lobby-compose">{roomCode && <button className="invite" onClick={() => send(true)}>Invita alla stanza {roomCode}</button>}<div><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} maxLength={240} placeholder={name ? "Scrivi nella lobby…" : "Inserisci prima il tuo nome"} disabled={!name} /><button onClick={() => send()} disabled={!name || !text.trim()}>Invia</button></div>{"Notification" in globalThis && Notification.permission === "default" && <button className="notify" onClick={enableNotifications}>Attiva avvisi per i nuovi inviti</button>}</div></aside>}</>;
}
