export type Language = "it" | "en" | "es" | "sq";
export const languages: Array<{ code: Language; flag: string; label: string }> = [
  { code: "it", flag: "🇮🇹", label: "Italiano" }, { code: "en", flag: "🇬🇧", label: "English" },
  { code: "es", flag: "🇪🇸", label: "Español" }, { code: "sq", flag: "🇦🇱", label: "Shqip" },
];

const it = {
  install:"Installa l’app",
  onlineMode:"Online", passPlayMode:"Passa e gioca", airplaneMode:"Modalità aereo", airplaneOn:"Attiva · partita completamente offline", airplaneOff:"Disattiva · usa la connessione", localPlayers:"Nomi dei 4 giocatori", botNames:"Nomi dei bot (facoltativi)", startLocal:"Inizia sullo stesso dispositivo", passDevice:"Passa il dispositivo a", revealHand:"Mostra le mie carte", translationFailed:"Traduzione non disponibile. Riprova.",
  exchangeYourTurn:"Scegli la carta da restituire", exchangeWaiting:"Scambio: tocca a", chooseExchange:"Scegli una carta dal 3 al 10", confirmExchange:"Conferma lo scambio", closedRound:"Giro chiuso · il mucchio resta sul tavolo",
    played:"ha giocato", watchPlay:"Guarda la giocata", playHistory:"Storico giocate", noPlays:"Nessuna giocata",
  how:"Come si gioca", classic:"Il classico dalmata · online", newGame:"Nuova partita", join:"Entra", yourName:"Il tuo nome", namePh:"Come ti chiami?", howMany:"Quante persone giocano?", youBots:"tu + 3 bot", humans:"umani", allHuman:"tutti umani", create:"Crea la stanza", orCode:"oppure entra con un codice", code:"CODICE", noDownload:"Nessun download. Funziona su iPhone, Android e desktop.", edition:"Edizione 2026", footer:"Gioca responsabilmente, passa strategicamente.", exit:"Esci", waiting:"Sala d’attesa", gather:"Raduna il tavolo", stillNeed:"Servono ancora", player:"giocatore", players:"giocatori", botsFill:"Gli altri posti saranno affidati ai bot.", roomCode:"Codice stanza", copied:"Link copiato!", copyInvite:"Copia link d’invito", waitingSeat:"In attesa…", team:"Squadra", amber:"Ambra", jade:"Giada", target:"Traguardo", you:"Tu", cards:"carte", lastCard:"ULTIMA MANO!", place:"posto", yourTurn:"Tocca a te", turnOf:"Turno di", matchOver:"Partita conclusa", handOver:"Mano conclusa", newRound:"Nuovo giro", freePlay:"gioca una combinazione libera", passed:"Hanno passato", yourHand:"La tua mano", selected:"selezionate", selectCards:"Seleziona le carte da giocare", pass:"Passo", play:"Gioca", newHand:"Nuova mano", home:"Torna all’inizio", tableLog:"Diario del tavolo", unexpected:"Errore inatteso.", lobby:"Lobby chat", lobbyTitle:"Lobby Murlan", organize:"Organizza una partita", lobbyEmpty:"La lobby è silenziosa. Rompi il ghiaccio.", enterRoom:"Entra", inviteRoom:"Invita alla stanza", writeLobby:"Scrivi nella lobby…", nameFirst:"Inserisci prima il tuo nome", send:"Invia", notify:"Attiva avvisi per i nuovi inviti", inviteMessage:"Vuoi giocare? Entra nella mia stanza.", notification:"nella lobby Murlan",
  suits:{H:"Cuori",D:"Quadri",C:"Fiori",S:"Picche",X:"Jolly"}, kinds:{single:"Singola",pair:"Coppia",triple:"Tris",straight:"Scala","triple-run":"Scala con tris","five-pairs":"Scala di 5 coppie",bomb:"Bomba","straight-flush":"Scala reale"},
  rulesTitle:"Come si gioca a Murlan", rulesEdition:"Regolamento 2026", rulesIntro:"Liberati di tutte le carte prima degli avversari. I posti opposti formano una squadra: Ambra (1 e 3) contro Giada (2 e 4).", rules:[
    ["1. Preparazione, squadre e obiettivo","Si usa un mazzo francese da poker di 54 carte, con Jolly Nero e Jolly Rosso. Si gioca sempre in quattro; i posti opposti sono compagni. Tutte le carte vengono distribuite: due giocatori ne ricevono 14 e due 13. Lo scopo della distribuzione è liberarsi delle carte prima degli avversari; l’ordine di uscita assegna 3, 2, 1 e 0 punti, sommati fra compagni nella modalità a squadre."],
    ["2. Ordine completo di carte e semi","Dal valore più basso al più alto: 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A, 2, Jolly Nero, Jolly Rosso. Nelle singole, coppie e tris il seme non spezza mai la parità: un 2 non può battere un altro 2. Il seme vale soltanto a parità di scala, nell’ordine ♠ Picche > ♣ Fiori > ♦ Quadri > ♥ Cuori; una scala con valore finale più alto vince comunque."],
    ["3. Singola, coppia e tris","Singola: una carta, per esempio 4♥. Coppia: due carte dello stesso valore, per esempio 4♥ 4♦. Tris: tre carte dello stesso valore, per esempio 4♥ 4♦ 4♠. La risposta deve avere lo stesso tipo e un valore superiore: un tris di 8 batte un tris di 7, ma una coppia non può rispondere a un tris."],
    ["4. Scale ordinarie","Scala semplice: almeno cinque valori consecutivi, senza obbligo di seme; esempio 3♥ 4♦ 5♠ 6♣ 7♥. Scala con tris centrale: cinque carte consecutive nelle quali il valore centrale è un tris e gli estremi sono singole; esempio 3♥ 4♣ 4♠ 4♦ 5♦. Scala di cinque coppie: dieci carte, cioè cinque coppie consecutive; esempio 3-3, 4-4, 5-5, 6-6, 7-7."],
    ["5. Come si batte una scala","Occorre una scala dello stesso tipo, con lo stesso numero di carte e più alta. Esempio: 3-4-5-6-7-8 viene battuta da 4-5-6-7-8-9, non da una scala di cinque o sette carte. Lo stesso principio vale per la scala con tris e per le cinque coppie."],
    ["6. Bomba e Scala Reale","Una Bomba è formata dalle quattro carte dello stesso valore, per esempio A♥ A♦ A♣ A♠. Una Scala Reale è formata da cinque carte consecutive dello stesso seme, per esempio 3♥ 4♥ 5♥ 6♥ 7♥. Entrambe interrompono e battono qualsiasi combinazione ordinaria. Una Bomba si batte solo con una Bomba superiore. Fra Scale Reali contano prima il valore finale e poi il seme."],
    ["7. Prima apertura, risposta e Passo","Nella prima distribuzione apre chi possiede il 3♠ e deve includerlo: può giocarlo singolo o dentro una combinazione valida. Il gioco prosegue in senso orario. Normalmente si risponde con lo stesso tipo, lo stesso numero di carte e un valore superiore; in alternativa si può usare una combinazione speciale. Chi non può o non vuole giocare dichiara Passo."],
    ["8. Chiusura del giro e mucchio sul tavolo","Quando tutti gli altri giocatori attivi hanno passato, il giro è chiuso. L’ultima giocata valida resta fisicamente nel mucchio insieme alle precedenti e chi l’ha effettuata apre il giro seguente con qualsiasi combinazione valida, anche più bassa o di tipo diverso. Esempio: dopo aver chiuso con un 2 può riaprire con un 3 singolo, una coppia, un tris o una scala."],
    ["9. Uscita e dichiarazione Ultima mano","Quando rimane una sola carta bisogna dichiarare “Ultima mano!”. Chi esaurisce le carte conquista la posizione disponibile. Se nessuno batte la sua ultima giocata, apre il giro seguente il giocatore successivo ancora attivo in senso orario. Le carte giocate restano nel mucchio fino alla fine della distribuzione."],
    ["10. Scambio fra primo e ultimo","Dalla seconda distribuzione, l’ultimo classificato consegna al primo la propria carta più alta; il primo restituisce una carta dal 3 al 10. Lo scambio è annullato se un giocatore possiede già entrambi i Jolly oppure se la carta ceduta completerebbe una Bomba di quattro carte uguali. Anche la carta restituita non può completare una Bomba al destinatario. Se lo scambio è annullato apre il primo; altrimenti apre l’ultimo."],
    ["11. Punteggio e fine della partita","I posti valgono 3, 2, 1 e 0 punti. Nella versione a squadre si sommano i punti dei compagni. Il traguardo iniziale è 21; se entrambe le squadre lo raggiungono o superano nella stessa distribuzione, sale a 31, poi 41 e infine 51. La partita termina quando una sola squadra supera il traguardo attivo."],
  ]
};

const en: typeof it = { ...it,
  install:"Install app",
  onlineMode:"Online", passPlayMode:"Pass & play", airplaneMode:"Airplane mode", airplaneOn:"On · fully offline game", airplaneOff:"Off · uses the connection", localPlayers:"Names of the 4 players", botNames:"Bot names (optional)", startLocal:"Start on this device", passDevice:"Pass the device to", revealHand:"Show my cards", translationFailed:"Translation unavailable. Try again.",
  exchangeYourTurn:"Choose the card to return", exchangeWaiting:"Exchange: waiting for", chooseExchange:"Choose one card from 3 to 10", confirmExchange:"Confirm exchange", closedRound:"Round closed · the pile stays on the table",
    played:"played", watchPlay:"Watch the play", playHistory:"Play history", noPlays:"No plays yet",
  how:"How to play", classic:"The Dalmatian classic · online", newGame:"New game", join:"Join", yourName:"Your name", namePh:"What is your name?", howMany:"How many people are playing?", youBots:"you + 3 bots", humans:"humans", allHuman:"all human", create:"Create room", orCode:"or join with a code", code:"CODE", noDownload:"No download. Works on iPhone, Android and desktop.", edition:"2026 Edition", footer:"Play wisely, pass strategically.", exit:"Leave", waiting:"Waiting room", gather:"Gather the table", stillNeed:"Still waiting for", player:"player", players:"players", botsFill:"Bots will fill the remaining seats.", roomCode:"Room code", copied:"Link copied!", copyInvite:"Copy invite link", waitingSeat:"Waiting…", team:"Team", amber:"Amber", jade:"Jade", target:"Target", you:"You", cards:"cards", lastCard:"LAST CARD!", place:"place", yourTurn:"Your turn", turnOf:"Turn of", matchOver:"Match over", handOver:"Hand over", newRound:"New round", freePlay:"play any valid combination", passed:"Passed", yourHand:"Your hand", selected:"selected", selectCards:"Select cards to play", pass:"Pass", play:"Play", newHand:"New hand", home:"Back to start", tableLog:"Table log", unexpected:"Unexpected error.", lobby:"Lobby chat", lobbyTitle:"Murlan Lobby", organize:"Organize a game", lobbyEmpty:"The lobby is quiet. Break the ice.", enterRoom:"Join", inviteRoom:"Invite to room", writeLobby:"Write in the lobby…", nameFirst:"Enter your name first", send:"Send", notify:"Enable alerts for new invitations", inviteMessage:"Want to play? Join my room.", notification:"in the Murlan lobby",
  suits:{H:"Hearts",D:"Diamonds",C:"Clubs",S:"Spades",X:"Joker"}, kinds:{single:"Single",pair:"Pair",triple:"Triple",straight:"Straight","triple-run":"Triple straight","five-pairs":"Five-pair straight",bomb:"Bomb","straight-flush":"Straight flush"},
  rulesTitle:"How to play Murlan", rulesEdition:"2026 Rules", rulesIntro:"Get rid of every card before your opponents. Opposite seats are partners: Amber (1 and 3) versus Jade (2 and 4).", rules:[
    ["1. Setup, teams and objective","Use a 54-card French deck with the Black and Red Jokers. Four people always play; opposite seats are partners. Deal every card: two players receive 14 and two receive 13. Players score 3, 2, 1 and 0 by finishing order; in team mode partners add those points."],
    ["2. Full card and suit order","Low to high: 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A, 2, Black Joker, Red Joker. Suits never break ties between singles, pairs or triples: one 2 cannot beat another 2. Suit matters only when equal straights tie, in the order ♠ Spades > ♣ Clubs > ♦ Diamonds > ♥ Hearts; a higher-ending straight always wins."],
    ["3. Single, pair and triple","A single is one card, such as 4♥. A pair is two cards of one rank, such as 4♥ 4♦. A triple is three cards of one rank, such as 4♥ 4♦ 4♠. A response must keep the same type and be higher: three 8s beat three 7s, but a pair cannot answer a triple."],
    ["4. Ordinary straights","A straight uses at least five consecutive ranks with any suits, for example 3♥ 4♦ 5♠ 6♣ 7♥. A triple-centre run has adjacent singles around a central triple, for example 3♥ 4♣ 4♠ 4♦ 5♦. A five-pair straight uses ten cards: 3-3, 4-4, 5-5, 6-6, 7-7."],
    ["5. Beating a straight","Play the same straight type, the same card count and a higher sequence. For example, 3-4-5-6-7-8 is beaten by 4-5-6-7-8-9, not by a five- or seven-card straight. The same rule applies to triple-centre runs and five-pair straights."],
    ["6. Bomb and Straight Flush","A Bomb is all four suits of one rank, such as A♥ A♦ A♣ A♠. A Straight Flush is five consecutive cards of one suit, such as 3♥ 4♥ 5♥ 6♥ 7♥. Either may interrupt and beat an ordinary play. Only a higher Bomb beats a Bomb. Straight Flushes compare final rank, then suit."],
    ["7. First lead, responses and passing","On the first deal, the holder of 3♠ leads and must include it, alone or in a valid combination. Play moves clockwise. Normally answer with the same type and card count at a higher value, or use a special combination. A player who cannot or chooses not to play says Pass."],
    ["8. Closing a round and the table pile","After every other active player passes, the round closes. All played cards stay physically in the centre pile. The last valid player leads again with any valid combination, even a lower or different type. Example: after closing with a 2, they may lead a low single, pair, triple or straight."],
    ["9. Going out and Last card","With one card remaining the player must announce “Last card!”. Going out secures the next finishing position. If nobody beats that final play, the next active player clockwise leads. Played cards remain in the pile until the deal is over."],
    ["10. First-last exchange","From the second deal onward, last place gives first place their highest card; first place returns a card ranked 3 through 10. Cancel the exchange if any player already holds both Jokers or if either transferred card would complete a four-of-a-kind Bomb for its recipient. After cancellation first place leads; otherwise last place leads."],
    ["11. Scoring and match end","Positions score 3, 2, 1 and 0. In team mode partners add their scores. The first target is 21; if both teams reach it in the same deal, raise it to 31, then 41 and finally 51. The match ends when only one team has cleared the active target."],
  ]
};

const es: typeof it = { ...it,
  install:"Instalar app",
  onlineMode:"En línea", passPlayMode:"Pasa y juega", airplaneMode:"Modo avión", airplaneOn:"Activo · partida totalmente offline", airplaneOff:"Inactivo · usa la conexión", localPlayers:"Nombres de los 4 jugadores", botNames:"Nombres de los bots (opcionales)", startLocal:"Empezar en este dispositivo", passDevice:"Pasa el dispositivo a", revealHand:"Mostrar mis cartas", translationFailed:"Traducción no disponible. Inténtalo de nuevo.",
  exchangeYourTurn:"Elige la carta que devolverás", exchangeWaiting:"Intercambio: turno de", chooseExchange:"Elige una carta del 3 al 10", confirmExchange:"Confirmar intercambio", closedRound:"Ronda cerrada · el montón queda en la mesa",
    played:"ha jugado", watchPlay:"Mira la jugada", playHistory:"Historial", noPlays:"Sin jugadas",
  how:"Cómo jugar", classic:"El clásico dálmata · online", newGame:"Nueva partida", join:"Entrar", yourName:"Tu nombre", namePh:"¿Cómo te llamas?", howMany:"¿Cuántas personas juegan?", youBots:"tú + 3 bots", humans:"humanos", allHuman:"todos humanos", create:"Crear sala", orCode:"o entra con un código", code:"CÓDIGO", noDownload:"Sin descargas. Funciona en iPhone, Android y ordenador.", edition:"Edición 2026", footer:"Juega con cabeza, pasa con estrategia.", exit:"Salir", waiting:"Sala de espera", gather:"Reúne la mesa", stillNeed:"Faltan", player:"jugador", players:"jugadores", botsFill:"Los bots ocuparán los asientos restantes.", roomCode:"Código de sala", copied:"¡Enlace copiado!", copyInvite:"Copiar enlace de invitación", waitingSeat:"Esperando…", team:"Equipo", amber:"Ámbar", jade:"Jade", target:"Objetivo", you:"Tú", cards:"cartas", lastCard:"¡ÚLTIMA CARTA!", place:"puesto", yourTurn:"Tu turno", turnOf:"Turno de", matchOver:"Partida terminada", handOver:"Mano terminada", newRound:"Nueva ronda", freePlay:"juega cualquier combinación válida", passed:"Han pasado", yourHand:"Tu mano", selected:"seleccionadas", selectCards:"Selecciona las cartas", pass:"Paso", play:"Jugar", newHand:"Nueva mano", home:"Volver al inicio", tableLog:"Diario de la mesa", unexpected:"Error inesperado.", lobby:"Chat del lobby", lobbyTitle:"Lobby Murlan", organize:"Organiza una partida", lobbyEmpty:"El lobby está en silencio. Rompe el hielo.", enterRoom:"Entrar", inviteRoom:"Invitar a la sala", writeLobby:"Escribe en el lobby…", nameFirst:"Primero escribe tu nombre", send:"Enviar", notify:"Activar avisos de nuevas invitaciones", inviteMessage:"¿Quieres jugar? Entra en mi sala.", notification:"en el lobby de Murlan",
  suits:{H:"Corazones",D:"Diamantes",C:"Tréboles",S:"Picas",X:"Joker"}, kinds:{single:"Individual",pair:"Pareja",triple:"Trío",straight:"Escalera","triple-run":"Escalera con trío","five-pairs":"Escalera de cinco parejas",bomb:"Bomba","straight-flush":"Escalera real"},
  rulesTitle:"Cómo jugar a Murlan", rulesEdition:"Reglamento 2026", rulesIntro:"Deshazte de todas tus cartas antes que los rivales. Los asientos opuestos forman equipo: Ámbar (1 y 3) contra Jade (2 y 4).", rules:[
    ["1. Preparación, equipos y objetivo","Se usa una baraja francesa de 54 cartas con Joker Negro y Rojo. Juegan cuatro; los asientos opuestos son compañeros. Se reparten todas las cartas: dos jugadores reciben 14 y dos 13. Los puestos valen 3, 2, 1 y 0 puntos, que se suman entre compañeros."],
    ["2. Orden de cartas y palos","De menor a mayor: 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A, 2, Joker Negro, Joker Rojo. El palo nunca desempata cartas individuales, parejas ni tríos: un 2 no vence a otro 2. Solo desempata escaleras iguales, en el orden ♠ Picas > ♣ Tréboles > ♦ Diamantes > ♥ Corazones; una escalera de valor final superior siempre vence."],
    ["3. Individual, pareja y trío","Individual: una carta, por ejemplo 4♥. Pareja: dos del mismo valor, por ejemplo 4♥ 4♦. Trío: tres del mismo valor, por ejemplo 4♥ 4♦ 4♠. La respuesta mantiene el tipo y sube el valor."],
    ["4. Escaleras ordinarias","Escalera: al menos cinco valores consecutivos, por ejemplo 3♥ 4♦ 5♠ 6♣ 7♥. Escalera con trío central: por ejemplo 3♥ 4♣ 4♠ 4♦ 5♦. Cinco parejas: diez cartas, 3-3, 4-4, 5-5, 6-6 y 7-7."],
    ["5. Cómo superar una escalera","Debe tener el mismo tipo y número de cartas, pero una secuencia superior. 3-4-5-6-7-8 pierde contra 4-5-6-7-8-9; una escalera de cinco o siete cartas no sirve como respuesta."],
    ["6. Bomba y Escalera Real","Bomba: las cuatro cartas de un valor, por ejemplo A♥ A♦ A♣ A♠. Escalera Real: cinco consecutivas del mismo palo. Ambas vencen cualquier combinación ordinaria. Una Bomba solo pierde contra otra superior; las Escaleras Reales comparan valor final y después palo."],
    ["7. Primera salida, respuesta y Paso","En el primer reparto abre quien tiene 3♠ y debe incluirlo, solo o en una combinación. Se juega en sentido horario. Se responde con el mismo tipo, igual cantidad y valor superior, o con una especial. También se puede declarar Paso."],
    ["8. Cierre de ronda y montón","Cuando todos los demás jugadores activos pasan, la ronda se cierra. Las cartas jugadas permanecen amontonadas en el centro. El autor de la última jugada abre libremente: tras cerrar con un 2 puede salir con una carta baja, pareja, trío o escalera."],
    ["9. Salida y Última carta","Con una carta se declara “¡Última carta!”. Quien se queda sin cartas obtiene la posición disponible. Si nadie supera su última jugada, abre el siguiente jugador activo en sentido horario. El montón permanece hasta terminar el reparto."],
    ["10. Intercambio entre primero y último","Desde el segundo reparto, el último entrega su carta más alta al primero y este devuelve una carta del 3 al 10. Se anula si algún jugador ya posee ambos Jokers o si cualquiera de las cartas transferidas completa una Bomba de cuatro iguales al destinatario. Si se anula abre el primero; si se completa abre el último."],
    ["11. Puntuación y final","Los puestos dan 3, 2, 1 y 0. Los compañeros suman. El objetivo empieza en 21; si ambos equipos lo alcanzan en el mismo reparto pasa a 31, luego 41 y 51. Termina cuando solo un equipo supera el objetivo activo."],
  ]
};

const sq: typeof it = { ...it,
  install:"Instalo aplikacionin",
  onlineMode:"Online", passPlayMode:"Kalo dhe luaj", airplaneMode:"Modaliteti avion", airplaneOn:"Aktiv · lojë plotësisht offline", airplaneOff:"Joaktiv · përdor lidhjen", localPlayers:"Emrat e 4 lojtarëve", botNames:"Emrat e boteve (opsionale)", startLocal:"Fillo në këtë pajisje", passDevice:"Kaloja pajisjen", revealHand:"Shfaq letrat e mia", translationFailed:"Përkthimi nuk është i disponueshëm. Provo përsëri.",
  exchangeYourTurn:"Zgjidh letrën që do të kthesh", exchangeWaiting:"Shkëmbimi: radha e", chooseExchange:"Zgjidh një letër nga 3 deri në 10", confirmExchange:"Konfirmo shkëmbimin", closedRound:"Raundi u mbyll · grumbulli mbetet në tryezë",
    played:"luajti", watchPlay:"Shiko lojën", playHistory:"Historiku i lojës", noPlays:"Asnjë lojë",
  how:"Si luhet", classic:"Klasikja dalmate · online", newGame:"Lojë e re", join:"Hyr", yourName:"Emri yt", namePh:"Si quhesh?", howMany:"Sa persona luajnë?", youBots:"ti + 3 bote", humans:"lojtarë", allHuman:"të gjithë lojtarë", create:"Krijo dhomën", orCode:"ose hyr me një kod", code:"KODI", noDownload:"Pa shkarkim. Punon në iPhone, Android dhe kompjuter.", edition:"Botimi 2026", footer:"Luaj me mend, paso me strategji.", exit:"Dil", waiting:"Dhoma e pritjes", gather:"Mblidh tryezën", stillNeed:"Duhen edhe", player:"lojtar", players:"lojtarë", botsFill:"Vendet e mbetura do t’i plotësojnë botet.", roomCode:"Kodi i dhomës", copied:"Lidhja u kopjua!", copyInvite:"Kopjo lidhjen e ftesës", waitingSeat:"Në pritje…", team:"Skuadra", amber:"Qelibar", jade:"Zhade", target:"Objektivi", you:"Ti", cards:"letra", lastCard:"LETRA E FUNDIT!", place:"vendi", yourTurn:"Radha jote", turnOf:"Radha e", matchOver:"Loja përfundoi", handOver:"Dora përfundoi", newRound:"Raund i ri", freePlay:"luaj çdo kombinim të vlefshëm", passed:"Pasuan", yourHand:"Letrat e tua", selected:"të zgjedhura", selectCards:"Zgjidh letrat për të luajtur", pass:"Pas", play:"Luaj", newHand:"Dorë e re", home:"Kthehu në fillim", tableLog:"Ditari i tryezës", unexpected:"Gabim i papritur.", lobby:"Biseda e lobit", lobbyTitle:"Lobi Murlan", organize:"Organizo një lojë", lobbyEmpty:"Lobi është i qetë. Fillo bisedën.", enterRoom:"Hyr", inviteRoom:"Fto në dhomë", writeLobby:"Shkruaj në lobi…", nameFirst:"Vendos më parë emrin", send:"Dërgo", notify:"Aktivizo njoftimet për ftesat", inviteMessage:"Dëshiron të luash? Hyr në dhomën time.", notification:"në lobin Murlan",
  suits:{H:"Zemra",D:"Karo",C:"Spathi",S:"Maça",X:"Xhol"}, kinds:{single:"Tek",pair:"Dyshe",triple:"Treshe",straight:"Shkallë","triple-run":"Shkallë me treshe","five-pairs":"Shkallë me pesë dyshe",bomb:"Bombë","straight-flush":"Shkallë mbretërore"},
  rulesTitle:"Si luhet Murlan", rulesEdition:"Rregullorja 2026", rulesIntro:"Hiqi të gjitha letrat para kundërshtarëve. Vendet përballë janë partnerë: Qelibari (1 dhe 3) kundër Zhades (2 dhe 4).", rules:[
    ["1. Përgatitja, skuadrat dhe qëllimi","Përdoret kuvertë franceze me 54 letra, me Xholin e Zi dhe të Kuq. Luajnë katër; vendet përballë janë partnerë. Shpërndahen të gjitha: dy marrin 14 dhe dy 13. Renditja jep 3, 2, 1 dhe 0 pikë, të cilat partnerët i mbledhin."],
    ["2. Renditja e letrave dhe shenjave","Nga më e ulëta: 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A, 2, Xholi i Zi, Xholi i Kuq. Shenja nuk zgjidh barazinë mes letrave teke, dysheve ose tresheve: një 2 nuk mund një 2 tjetër. Shenja vlen vetëm kur dy shkallë janë të barabarta, me rendin ♠ Maça > ♣ Spathi > ♦ Karo > ♥ Zemra; shkalla që mbaron më lart fiton gjithmonë."],
    ["3. Tek, dyshe dhe treshe","Tek: një letër, p.sh. 4♥. Dyshe: dy me të njëjtën vlerë, p.sh. 4♥ 4♦. Treshe: tri me të njëjtën vlerë, p.sh. 4♥ 4♦ 4♠. Përgjigjja ruan llojin dhe rrit vlerën."],
    ["4. Shkallët e zakonshme","Shkallë: të paktën pesë vlera radhazi, p.sh. 3♥ 4♦ 5♠ 6♣ 7♥. Shkallë me treshe në mes: 3♥ 4♣ 4♠ 4♦ 5♦. Pesë dyshe: dhjetë letra, 3-3, 4-4, 5-5, 6-6, 7-7."],
    ["5. Si mundet një shkallë","Duhet i njëjti lloj dhe numër letrash, por sekuencë më e lartë. 3-4-5-6-7-8 mundet nga 4-5-6-7-8-9; një shkallë me pesë ose shtatë letra nuk vlen si përgjigje."],
    ["6. Bomba dhe Shkalla Mbretërore","Bombë janë katër shenjat e një vlere, p.sh. A♥ A♦ A♣ A♠. Shkallë Mbretërore janë pesë letra radhazi të së njëjtës shenjë. Të dyja mundin lojërat e zakonshme. Bombën e mund vetëm një Bombë më e lartë; Shkallët krahasojnë vlerën e fundit e pastaj shenjën."],
    ["7. Hapja e parë, përgjigjja dhe Pas","Në shpërndarjen e parë hap ai që ka 3♠ dhe duhet ta përfshijë, vetëm ose në kombinim. Loja ecën në drejtim të akrepave. Përgjigjja ka të njëjtin lloj e numër, por vlerë më të lartë, ose është speciale. Lejohet edhe Pas."],
    ["8. Mbyllja e raundit dhe grumbulli","Kur të gjithë lojtarët e tjerë aktivë pasojnë, raundi mbyllet. Letrat e luajtura mbeten grumbull në qendër. Lojtari i fundit hap lirshëm: pas një 2 mund të luajë një letër të ulët, dyshe, treshe ose shkallë."],
    ["9. Dalja dhe Letra e fundit","Me një letër duhet thënë “Letra e fundit!”. Ai që mbaron merr vendin e radhës. Nëse askush nuk mund lojën e fundit, hap lojtari tjetër aktiv në drejtim orar. Grumbulli mbetet deri në fund të shpërndarjes."],
    ["10. Shkëmbimi i të parit me të fundit","Nga shpërndarja e dytë, i fundit i jep të parit letrën më të lartë dhe i pari kthen një letër nga 3 deri në 10. Shkëmbimi anulohet nëse një lojtar ka tashmë të dy Xholat ose nëse njëra nga letrat e shkëmbyera plotëson një Bombë me katër letra të njëjta te marrësi. Kur anulohet hap i pari; ndryshe hap i fundit."],
    ["11. Pikët dhe fundi","Vendet japin 3, 2, 1 dhe 0 pikë. Partnerët i mbledhin. Objektivi nis në 21; nëse të dyja skuadrat e arrijnë në të njëjtën shpërndarje, kalon në 31, pastaj 41 dhe 51. Loja mbaron kur vetëm një skuadër kalon objektivin aktiv."],
  ]
};

export const translations = { it, en, es, sq };
export type Copy = typeof it;

export function translateLog(line: string, lang: Language) {
  if (lang === "it") return line;
  const c = translations[lang];
  return line
    .replace("La partita è iniziata. Il 3♠ apre la prima mano.", lang === "en" ? "The game has started. 3♠ opens the first hand." : lang === "es" ? "La partida ha comenzado. El 3♠ abre la primera mano." : "Loja filloi. 3♠ hap dorën e parë.")
    .replace(" gioca ", lang === "en" ? " plays " : lang === "es" ? " juega " : " luan ")
    .replace(" passa.", lang === "en" ? " passes." : lang === "es" ? " pasa." : " pason.")
    .replace(" apre un nuovo giro.", lang === "en" ? " opens a new round." : lang === "es" ? " abre una nueva ronda." : " hap një raund të ri.")
    .replace("Mano conclusa:", c.handOver + ":")
    .replace("Squadra Ambra", `${c.team} ${c.amber}`).replace("Squadra Giada", `${c.team} ${c.jade}`)
    .replace(" ha chiuso in ", lang === "en" ? " finished in " : lang === "es" ? " terminó en " : " përfundoi në ")
    .replace(" posizione.", lang === "en" ? " place." : lang === "es" ? " puesto." : " vend.");
}

export function translateError(message: string, lang: Language) {
  if (lang === "it") return message;
  const map: Array<[string,string,string,string]> = [
    ["Non è il tuo turno","It is not your turn","No es tu turno","Nuk është radha jote"],
    ["Una carta scelta non è disponibile","A selected card is no longer available","Una carta seleccionada ya no está disponible","Një letër e zgjedhur nuk është më e disponueshme"],
    ["Questa combinazione non è valida","This combination is not valid","Esta combinación no es válida","Ky kombinim nuk është i vlefshëm"],
    ["La prima giocata deve contenere il 3♠","The opening play must include 3♠","La primera jugada debe incluir el 3♠","Loja e parë duhet të përmbajë 3♠"],
    ["Devi giocare lo stesso tipo più alto","Play the same type at a higher value, or a special combination","Debes jugar el mismo tipo con valor superior o una combinación especial","Duhet të luash të njëjtin lloj me vlerë më të lartë ose një kombinim special"],
    ["Chi apre il giro non può passare","The player opening the round cannot pass","Quien abre la ronda no puede pasar","Lojtari që hap raundin nuk mund të pasojë"],
    ["Stanza non trovata","Room not found","Sala no encontrada","Dhoma nuk u gjet"],
    ["Codice stanza non valido","Invalid room code","Código de sala no válido","Kodi i dhomës nuk është i vlefshëm"],
  ];
  const idx = lang === "en" ? 1 : lang === "es" ? 2 : 3; const found = map.find(([it]) => message.includes(it));
  return found ? found[idx] : translations[lang].unexpected;
}
